env:
  global:
    CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID"
    CC_TEST_REPORTER_TYPE=

language: node_js
node_js:
  - v11
  - v10
  - v8
  - v6

os:
  - linux
  - osx

git:
  depth: 1

before_install:
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"

install:
  - npm i

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CC_REPORTER_TYPE="linux"  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC_REPORTER_TYPE="darwin"   ; fi
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-${CC_REPORTER_TYPE}-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - npm run ci:coverage:codacy
  - npm run ci:coverage:coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
# - FOSSA_API_KEY=$FOSSA_API_KEY fossa analyze
# - fossa test

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx travis-deploy-once "npx semantic-release"
