env:
  global:
    CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID"
    CC_TEST_REPORTER_TYPE=

language: node_js
node_js:
  - v11
  - v10
  - v8
  - v6

os:
  - linux
  - osx

git:
  depth: 1

before_install:
  # npm
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
  # FOSSA: install fossa-cli to run Provided Builds
  # @see https://docs.fossa.com/docs/provided-builds
  - chmod +x ./.github/ci/legal/fossa-init.sh
  - chmod +x ./.github/ci/qa/code-climate-init.sh

install:
  - npm i

before_script:
  - ./.github/ci/legal/fossa-init.sh
  - ./.github/ci/qa/code-climate-init.sh
  - $TRAVIS_BUILD_DIR/cc-test-reporter before-build || exit 0

script:
  - npm test

after_script:
  - npm run ci:coverage:codacy
  - npm run ci:coverage:coveralls
  - $TRAVIS_BUILD_DIR/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || exit 0

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx travis-deploy-once "npx semantic-release"
