# 1. Set-up
env:
  global:
    CC_TEST_REPORTER_ID="$CC_TEST_REPORTER_ID"
    CC_TEST_REPORTER_TYPE=

language: node_js

# 1.1. Run quality assurance (QA) gates on all
#      supported Node.js versions...
node_js:
  - v11
  - v10
  - v8
  - v6

# 1.2. ...on both Linux and MacOS
#       @see https://github.com/nodejs/Release#release-schedule
os:
  - linux
  - osx

# 1.3. Do a shallow-clone to speed up analysis
#      (fail fast!)
git:
  depth: 1

# before_install:
#   - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
#   # FOSSA: install fossa-cli to run Provided Builds
#   # @see https://docs.fossa.com/docs/provided-builds
#   - chmod +x ./.github/ci/legal/fossa-init.sh
#   - chmod +x ./.github/ci/qa/code-climate-init.sh

# install:
#   - npm i

# before_script:
#   - ./.github/ci/legal/fossa-init.sh
#   - ./.github/ci/qa/code-climate-init.sh
#   - $TRAVIS_BUILD_DIR/cc-test-reporter before-build || exit 0

# script:
#   - npm test

# after_script:
#   - npm run ci:coverage:codacy
#   - npm run ci:coverage:coveralls
#   - $TRAVIS_BUILD_DIR/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || exit 0

jobs:
  include:
    - stage: install
      script:
        # 2. Before installation (before_install) steps:

        # 2.1. Set up dependency manager (node package manager "npm")
        - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"

        # 2.2. FOSS license-compliance evaluator (fossa-cli for Provided Builds)
        #      Grant execution permission
        #      @see https://docs.fossa.com/docs/provided-builds
        - chmod +x ./.github/ci/legal/fossa-init.sh

        # 2.3. CodeClimate source code quality assessor
        #    Grant execution permission
        - chmod +x ./.github/ci/qa/code-climate-init.sh

        # 3. Installation step (install):
        - npm install

    - stage: test
      name: "Test, Verify Coverage Thresholds, Check License Compliance, and Review Code Quality"
      script:
        # 4.   Before running unit tests...
        # 4.1. Initialize FOSSA for OSS license compliance evaluation
        - ./.github/ci/legal/fossa-init.sh

        # 4.2. Initialize CodeClimate for quality assurance code review
        #      automatically sent as comments during a Merge Request
        #      to master.
        - ./.github/ci/qa/code-climate-init.sh

        # 4.3. Initialize CodeClimate Code Coverage reporter
        - $TRAVIS_BUILD_DIR/cc-test-reporter before-build || exit 0

        # 5.   Test!
        - npm test

        # 5.1. Share code coverage with
        #      - Codacy,
        #      - Coveralls,
        - npm run ci:coverage

        #      - and CodeClimate
        - $TRAVIS_BUILD_DIR/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT || exit 0

    - stage: audit
      name: "Audit Dependencies for Known Vulnerabilities"
      # 6. Security audit
      script: npm run security:audit:dependencies
    - stage: release
      name: "Publish to NPM (public registry)"
      # 7. Deploy from the lastest Node.js Long-Term Support
      #    (LTS) build.
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # 7.1. Bump semantic version by commit message headers' "type"
          # 7.2. Generate GitHub Release Notes
          # 7.3. Append change list to the CHANGELOG.md
          # 7.4. Bump package.json#version
          # 7.5. Stage and commit all of the above
          # 7.6. Push to Git remote origin master
          # 7.7. Trigger all CI quality gates on master
          # 7.8. All gates pass (steps 1-6)? Bump semver and
          # 7.8.1. Squash and merge into origin/master
          # 7.8.2. Publish a GitHub release with notes and CHANGELOG
          # 7.8.3. Publish on NPM (including README)
          # 7.9.  Any gate fails? Roll back and abort all release steps.
          - npx semantic-release
