language: node_js
node_js:
  - v11
  - v10
  - v8
  - v6

os:
- linux
- osx

git:
  depth: 1
before_install:
- "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest"
- curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
install:
- npm i
script:
- npm test
after_script:
- npm i --save-optional codacy-coverage
- npm run ci:coverage:codacy
- npm run ci:coverage:coveralls
- FOSSA_API_KEY=$FOSSA_API_KEY fossa analyze
- fossa test
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx travis-deploy-once "npx semantic-release"
